---
abstract: ~
author:
  - 'Yuval Kogman C<nothingmuch@woobling.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Authenticaton-Store-Htpasswd
no_index:
  directory:
    - inc
    - t
requires:
  Authen::Htpasswd: 0.13
  Catalyst::Plugin::Authentication: 0.10006
  Class::Accessor::Fast: 0
  Crypt::PasswdMD5: 0
version: 1.001
